# Prometheus configuration for Sermon Uploader monitoring
# This configuration sets up monitoring for the sermon uploader system

global:
  scrape_interval: 15s
  evaluation_interval: 15s

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

# Load alerting rules
rule_files:
  - "alerts.yml"

# Scrape configurations
scrape_configs:
  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Sermon Uploader main service
  - job_name: 'sermon-uploader'
    static_configs:
      - targets: ['localhost:8000']
    metrics_path: '/api/metrics'
    scrape_interval: 30s
    scrape_timeout: 10s

  # MinIO metrics (if available)
  - job_name: 'minio'
    static_configs:
      - targets: ['localhost:9000']
    metrics_path: '/minio/v2/metrics/cluster'
    scrape_interval: 30s
    scrape_timeout: 10s

  # Node exporter for system metrics
  - job_name: 'node'
    static_configs:
      - targets: ['localhost:9100']
    scrape_interval: 15s

  # Docker container metrics (if cAdvisor is available)
  - job_name: 'docker'
    static_configs:
      - targets: ['localhost:8080']
    scrape_interval: 30s

  # Custom health check endpoint
  - job_name: 'health-check'
    static_configs:
      - targets: ['localhost:8000']
    metrics_path: '/api/health'
    scrape_interval: 15s
    scrape_timeout: 5s
    # Convert health check response to metrics
    metric_relabel_configs:
      - source_labels: [__name__]
        target_label: __name__
        replacement: sermon_uploader_health_status