name: PR Automation and Protection

on:
  issues:
    types: [assigned, labeled]
  pull_request:
    types: [opened, synchronize, closed]
  pull_request_review:
    types: [submitted]

jobs:
  create-feature-branch:
    if: github.event.action == 'assigned' || (github.event.action == 'labeled' && contains(github.event.label.name, 'ready-for-implementation'))
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Create feature branch for issue
      run: |
        ISSUE_NUMBER=${{ github.event.issue.number }}
        ISSUE_TITLE="${{ github.event.issue.title }}"
        
        # Sanitize title for branch name
        BRANCH_NAME="issue-${ISSUE_NUMBER}-$(echo "$ISSUE_TITLE" | tr '[:upper:]' '[:lower:]' | sed 's/[^a-z0-9]/-/g' | sed 's/--*/-/g' | sed 's/-$//')"
        
        echo "Creating branch: $BRANCH_NAME"
        
        # Create and push branch
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git checkout -b "$BRANCH_NAME"
        
        # Create initial commit with issue template
        mkdir -p ".issue-tracking"
        cat > ".issue-tracking/issue-${ISSUE_NUMBER}.md" << EOF
        # Issue #${ISSUE_NUMBER}: ${{ github.event.issue.title }}
        
        **Status**: Implementation in progress
        **Assignee**: ${{ github.event.issue.assignee.login }}
        **Labels**: ${{ join(github.event.issue.labels.*.name, ', ') }}
        
        ## Implementation Checklist:
        - [ ] Code changes completed
        - [ ] Local testing passed
        - [ ] Ready for PR review
        - [ ] Claude Code verification requested
        
        ## Review Process:
        1. Create PR when implementation complete
        2. Request @claude-code review in PR
        3. Address any review comments
        4. Get approval before merge
        
        **Related Issue**: Closes #${ISSUE_NUMBER}
        EOF
        
        git add ".issue-tracking/issue-${ISSUE_NUMBER}.md"
        git commit -m "Create feature branch for issue #${ISSUE_NUMBER}

        - ${{ github.event.issue.title }}
        - Branch: $BRANCH_NAME
        - Auto-created for implementation tracking
        
        Related: #${ISSUE_NUMBER}"
        
        git push origin "$BRANCH_NAME"
        
        # Comment on issue with branch info
        gh issue comment ${{ github.event.issue.number }} --body "🌿 **FEATURE BRANCH CREATED**
        
        **Branch**: \`$BRANCH_NAME\`
        **Next Steps**:
        1. Switch to feature branch: \`git checkout $BRANCH_NAME\`
        2. Implement the task requirements  
        3. Test your changes locally
        4. Push commits: \`git push origin $BRANCH_NAME\`
        5. Create PR when ready: \`gh pr create\`
        
        **Protection**: Direct pushes to \`master\` are discouraged. Use this feature branch → PR → review → merge workflow.
        
        ⚠️ **Remember**: No PR will be merged without @claude-code review and approval!"
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  pr-validation:
    if: github.event.action == 'opened' || github.event.action == 'synchronize'
    runs-on: ubuntu-latest
    steps:
    - name: Validate PR requirements
      run: |
        PR_NUMBER=${{ github.event.pull_request.number }}
        PR_BODY="${{ github.event.pull_request.body }}"
        PR_TITLE="${{ github.event.pull_request.title }}"
        
        echo "🔍 Validating PR #${PR_NUMBER}..."
        
        VALIDATION_FAILED=false
        ISSUES=()
        
        # Check if PR references an issue
        if ! echo "$PR_BODY" | grep -iE "(closes?|fixes?|resolves?) #[0-9]+" > /dev/null; then
          ISSUES+=("❌ PR must reference an issue (e.g., 'Closes #123')")
          VALIDATION_FAILED=true
        fi
        
        # Check for implementation evidence
        if ! echo "$PR_BODY" | grep -E "(test|verify|implement|complete)" > /dev/null; then
          ISSUES+=("⚠️ PR should describe what was implemented/tested")
        fi
        
        # Check for reviewer request
        if ! echo "$PR_BODY" | grep -i "claude-code" > /dev/null; then
          ISSUES+=("⚠️ PR should request @claude-code review")
        fi
        
        if [ "$VALIDATION_FAILED" = true ]; then
          echo "::error::PR validation failed"
          
          # Comment with issues
          COMMENT="🚨 **PR VALIDATION FAILED**

          The following issues were found:
          $(printf '%s\n' "${ISSUES[@]}")
          
          **Required PR Format**:
          - Must reference issue: \`Closes #123\`
          - Should describe implementation
          - Should request @claude-code review
          - Should include testing evidence
          
          Please update the PR description to address these issues."
          
          gh pr comment $PR_NUMBER --body "$COMMENT"
        else
          echo "✅ PR validation passed"
          
          # Add success comment
          gh pr comment $PR_NUMBER --body "✅ **PR VALIDATION PASSED**
          
          PR meets basic requirements. Awaiting @claude-code review.
          
          **Review Process**:
          1. @claude-code will review code and implementation
          2. Address any review feedback  
          3. Get approval before merge
          4. Merge will auto-close related issue"
        fi
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  check-review-status:
    if: github.event.action == 'submitted' && github.event.review.state == 'approved'
    runs-on: ubuntu-latest
    steps:
    - name: Check if PR can be merged
      run: |
        PR_NUMBER=${{ github.event.pull_request.number }}
        REVIEWER="${{ github.event.review.user.login }}"
        
        echo "✅ PR #${PR_NUMBER} approved by ${REVIEWER}"
        
        # Check if this was Claude Code approval (via your account)
        if [ "$REVIEWER" = "greastern" ]; then
          echo "📝 Adding merge instructions"
          
          gh pr comment $PR_NUMBER --body "🎉 **APPROVED FOR MERGE**
          
          ✅ Code review completed by @claude-code (via @greastern)
          ✅ All checks passed
          ✅ Ready for merge
          
          **To merge**:
          - Use 'Squash and merge' to keep history clean
          - Will automatically close related issue
          - Will trigger deployment if on master branch
          
          🚀 Safe to merge when ready!"
        fi
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  auto-close-issue:
    if: github.event.action == 'closed' && github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - name: Close related issue and update tracking
      run: |
        PR_NUMBER=${{ github.event.pull_request.number }}
        PR_BODY="${{ github.event.pull_request.body }}"
        
        # Extract issue number from PR body
        ISSUE_NUM=$(echo "$PR_BODY" | grep -oiE "(closes?|fixes?|resolves?) #([0-9]+)" | grep -oE "[0-9]+" | head -1)
        
        if [ -n "$ISSUE_NUM" ]; then
          echo "🔗 PR merged, closing issue #${ISSUE_NUM}"
          
          gh issue comment $ISSUE_NUM --body "✅ **AUTOMATICALLY CLOSED**
          
          **Merged PR**: #${PR_NUMBER}
          **Implementation**: Completed and merged to master
          **Status**: Task verified and complete
          
          This issue was closed automatically when PR #${PR_NUMBER} was merged.
          
          🎉 Task successfully implemented with proper review process!"
          
          gh issue close $ISSUE_NUM
        else
          echo "⚠️ No issue number found in PR body"
        fi
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}